### ISSUE TITLE
Allow loading adjacent configuration files in Release(-R2R) builds

### ISSUE THREAD

**Issue by dodexahedron** [snapsinazfs/snapsinazfs#24]
Sorry @dodexahedron, sleeping time :-)
I hate snap. I unregistered and uninstall "Ubuntu-22.04". Then I reinstalled and installed `dotnet` following the instructions at https://stackoverflow.com/a/73899341/4872289. Now `dotnet` is correctly installed.
```bash
:~$ dotnet --info
.NET SDK:
 Version:   7.0.109
 Commit:    3e9283a8e9

Runtime Environment:
 OS Name:     ubuntu
 OS Version:  22.04
 OS Platform: Linux
 RID:         ubuntu.22.04-x64
 Base Path:   /usr/lib/dotnet/sdk/7.0.109/

Host:
  Version:      7.0.9
  Architecture: x64
  Commit:       8e9a17b221

.NET SDKs installed:
  6.0.120 [/usr/lib/dotnet/sdk]
  7.0.109 [/usr/lib/dotnet/sdk]

.NET runtimes installed:
  Microsoft.AspNetCore.App 6.0.20 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.AspNetCore.App 7.0.9 [/usr/lib/dotnet/shared/Microsoft.AspNetCore.App]
  Microsoft.NETCore.App 6.0.20 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]
  Microsoft.NETCore.App 7.0.9 [/usr/lib/dotnet/shared/Microsoft.NETCore.App]

Other architectures found:
  None

Environment variables:
  DOTNET_ROOT       [/usr/lib/dotnet]

global.json file:
  Not found

Learn more:
  https://aka.ms/dotnet/info

Download .NET:
  https://aka.ms/dotnet/download
```
When trying running I get this error:

```bash
:/home/bdisp/source/snapsinazfs# ./publish/Release-R2R/SnapsInAZfs
2023-07-31 14:48:01.6995|DEBUG |Getting base configuration from files
2023-07-31 14:48:01.7148|DEBUG |Overriding settings using arguments from command line.
Unhandled exception. System.IO.FileNotFoundException: Path to zfs utility must be a valid and accessible path.
   at SnapsInAZfs.Interop.Zfs.ZfsCommandRunner.ZfsCommandRunner..ctor(String pathToZfs, String pathToZpool) in /home/bdisp/source/snapsinazfs/SnapsInAZfs.Interop/Zfs/ZfsCommandRunner/ZfsCommandRunner.cs:line 54
   at SnapsInAZfs.Program.ServiceInstanceProvider(IServiceProvider arg) in /home/bdisp/source/snapsinazfs/SnapsInAZfs/Program.cs:line 148
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitFactory(FactoryCallSite factoryCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitIEnumerable(IEnumerableCallSite enumerableCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.CreateServiceAccessor(Type serviceType)
   at System.Collections.Concurrent.ConcurrentDictionary`2.GetOrAdd(TKey key, Func`2 valueFactory)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService(IServiceProvider provider, Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetRequiredService[T](IServiceProvider provider)
   at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
   at SnapsInAZfs.Program.Main(String[] argv) in /home/bdisp/source/snapsinazfs/SnapsInAZfs/Program.cs:line 133
   at SnapsInAZfs.Program.<Main>(String[] argv)
Aborted
```
If it's secret credentials I understand and then I'll not insist and I'll stopping trying. Thanks.

PS: Why you added the `SnapsInAZfs.sln` into` .gitignore`? That helps a lot to load projects and artifacts. If was to avoid show secrets then is better using user secrets with environments variables.
**Edit:**
Sorry ignore what I said about `SnapsInAZfs.sln`. I confused with the `*.sln.iml`.

_Originally posted by @BDisp in https://github.com/snapsinazfs/snapsinazfs/issues/23#issuecomment-1658436329_
 

Adjacent configuration file loading should be allowed by default in release builds, and only disabled via an explicit option during compilation.

**Comment by dodexahedron** [comment]
This has been implemented for RC3, which will be tagged for release shortly.

There is also a new `make help` recipe, which shows a man page with detailed installation documentation, partially inspired by our conversations here and on the Terminal.Gui issue.

Closing this issue.
